### ISSUE TITLE
Einzel-Status-Abfrage

### ISSUE THREAD

**Issue by PatrickPutz** [PatrickPutz/LedController#1]
- ApiService erweitern um getLight(id) -Methode, die den Status einer spezifischen LED abruft
- ApiServiceImpl dabei refactoren, sodass gemeinsamer Code in eine Methode ausgelagert wird
- Keine Code-Duplication zwischen getLights() und getLight(id)

**Comment by LeoTanner** [comment]
works as intended, good job. You deserve a pat on the back
